[package]
name = "flappy_bird"
version = "0.1.0"
edition = "2021"
author = ["yoyozaemon"]
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tetra = "0.6"
rand = "0.8.0"
